# Matrixarithmetik in numpy

Matrizen lassen sich mit "geschachtelten" numpy arrais darstellen:

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
B = np.array([[-1,1],[2,-2]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[-1,  1],
       [ 2, -2]])

Wie man sieht, werden die Einträge der Matrix als eine Liste von Zeilen eingegeben, wobei jede Zeile eine Liste von Zahlen ist. Ein Spaltenvektor würde also so konstruiert:

In [5]:
v = np.array([[2],[1]])

Einzelne Einträge einer Matrix erhält man mit `A[i,j]` für den Eintrag von `A` in der `i`-ten Zeile und `j`-ten Spalte. Dabei ist aber zu beachten, dass man mit dem Zählen nicht bei $1$, sondern bei $0$ beginnt:

In [6]:
A[ 0, 1 ]

2

Rechenoperationen mit arrays erfolgen normalerweise komponentenweise. Das ist genau, was man bei der Addition von Matrizen will. Nur bei der Addition möchte man doch eher die Matrixmultiplikation aus der linearen Algebra haben. Daher verwendet man für die Multiplikation eine spezielle Funktion:

In [7]:
A + B

array([[0, 3],
       [5, 2]])

In [8]:
A * B    # komponentenweise

array([[-1,  2],
       [ 6, -8]])

In [9]:
np.matmul( A, B )  #Matrixprodukt aus der Linearen Algebra

array([[ 3, -3],
       [ 5, -5]])

Auf diese Weise kann man natürlich auch ein Matrix-Vektor-Produkt berechnen:

In [10]:
np.matmul( A, v )

array([[ 4],
       [10]])

Natürlich kann man auch Funktionen definieren, die eine Matrix zurückgeben:

In [11]:
# Zu einer Liste X von Punkten wird an Stelle (i,j)
# das i-te Listenelement zur j-ten Potenz geschrieben
# Die Länge der Liste X erhält man mit len(X)
def Vandermonde ( X ):
    return np.array( [ [x**j for j in range( len( X ) ) ] for x in X ] )

In [12]:
Vandermonde( [ 1, 2.5, 3 ] )

array([[1.  , 1.  , 1.  ],
       [1.  , 2.5 , 6.25],
       [1.  , 3.  , 9.  ]])

Für das Invertieren von Matrizen benötigt man eine Funktion aus `np.linalg`.

In [13]:
np.linalg.inv( Vandermonde( [ 1, 2.5, 3 ] ) )

array([[ 2.5       , -4.        ,  2.5       ],
       [-1.83333333,  5.33333333, -3.5       ],
       [ 0.33333333, -1.33333333,  1.        ]])

In [14]:
np.matmul(np.linalg.inv( Vandermonde( [ 1, 2.5, 3 ] ) ) , Vandermonde( [ 1, 2.5, 3 ] ) ) 
# Es könnten hier natürlich Rundungsfehler auftreten

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Versucht man, eine nicht-invertierbare Matrix zu invertieren, entsteht ein Fehler:

In [15]:
np.linalg.inv( B )

LinAlgError: Singular matrix

Will man sicher gehen, dass man keine nicht-invertierbare Matrix invertiert, könnte man zuerst die Determinante berechnen lassen, denn diese ist ja für singuläre Matrizen Null:

In [16]:
if np.linalg.det( A ) == 0:
    print( "Matrix ist singulär" )
else:
    print( "Wir können versuchen, zu invertieren" )

Wir können versuchen, zu invertieren


In [17]:
if np.linalg.det( B ) == 0:
    print( "Matrix ist singulär" )
else:
    print( "Wir können versuchen, zu invertieren" )

Matrix ist singulär


Aber: Die Berechnung der Determinante ist aufwändig und ein Wert ungleich Null kann auch durch Rundungsfehler zustande kommen. Also ist es besser, einfach das Invertieren zu *versuchen*, und ggf. den Fehler "abzufangen". Dies geht durch `try: <Codeblock> except <Fehlertyp> as <Variable>: <Codeblock>`:

In [18]:
try:
    print( np.linalg.inv( A ) )
except np.linalg.LinAlgError as Fehler:
    print( Fehler )

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
try:
    print( np.linalg.inv( B ) )
except np.linalg.LinAlgError as Fehler:
    print( Fehler )

Singular matrix
